from typing import Final
EXTENSION_NAME: Final[str] = "PROJECT_ARCHITECT"
TARGET_NODE_LABEL: Final[str] = "TRIPLANAR_MAPPING"
SCALE_FIELD_NAME: Final[str] = "triplanar_scale"
LIGHTMAP_NODE_LABEL: Final[str] = "LIGHTMAP"
NORMAL_NODE_LABEL: Final[str] = "NORMAL"
EMISSIVE_NODE_LABEL: Final[str] = "EMISSIVE"
ALBEDO_TEXTURE_LABEL: Final[str] = "ALBEDO_TEXTURE"
NORMAL_TEXTURE_LABEL: Final[str] = "NORMAL_TEXTURE"
METALLIC_TEXTURE_LABEL: Final[str] = "METALLIC_TEXTURE"
ROUGHNESS_TEXTURE_LABEL: Final[str] = "ROUGHNESS_TEXTURE"
ALPHA_TEXTURE_LABEL: Final[str] = "ALPHA_TEXTURE"
AO_TEXTURE_LABEL: Final[str] = "AO_TEXTURE"
EMISSIVE_TEXTURE_LABEL: Final[str] = "EMISSIVE_TEXTURE"
ALBEDO_TRIPLANAR_TEXTURE_LABEL: Final[str] = "ALBEDO_TRIPLANAR_TEXTURE"
NORMAL_TRIPLANAR_TEXTURE_LABEL: Final[str] = "NORMAL_TRIPLANAR_TEXTURE"
METALLIC_TRIPLANAR_TEXTURE_LABEL: Final[str] = "METALLIC_TRIPLANAR_TEXTURE"
ROUGHNESS_TRIPLANAR_TEXTURE_LABEL: Final[str] = "ROUGHNESS_TRIPLANAR_TEXTURE"
ALPHA_TRIPLANAR_TEXTURE_LABEL: Final[str] = "ALPHA_TRIPLANAR_TEXTURE"
AO_TRIPLANAR_TEXTURE_LABEL: Final[str] = "AO_TRIPLANAR_TEXTURE"
EMISSIVE_TRIPLANAR_TEXTURE_LABEL: Final[str] = "EMISSIVE_TRIPLANAR_TEXTURE"
LIGHTMAP_PIXELS_PER_METER: Final[int] = 128
LIGHTMAP_MAX_RESOLUTION: Final[int] = 1024
BAKE_SAMPLES: Final[int] = 2560
BAKE_MARGIN: Final[int] = 4
EXCLUDED_COLLECTIONS: Final[set[str]] = {'COLLIDERS', 'COMMANDS'}


