import re
from typing import Final
EXTENSION_NAME: Final[str] = "PROJECT_ARCHITECT"
TARGET_NODE_LABEL: Final[str] = "TRIPLANAR_MAPPING"
SCALE_FIELD_NAME: Final[str] = "triplanar_scale"
LIGHTMAP_NODE_LABEL: Final[str] = "LIGHTMAP"
NORMAL_NODE_LABEL: Final[str] = "NORMAL"
EMISSIVE_NODE_LABEL: Final[str] = "EMISSIVE"

def _compile_label_regex(pattern: str) -> re.Pattern[str]:
    return re.compile(pattern, re.IGNORECASE)

ALBEDO_TEXTURE_LABEL_PATTERN: Final[str] = r"ALBEDO_TEXTURE|ALBEDO|BASE_COLOR|BASE COLOR"
NORMAL_TEXTURE_LABEL_PATTERN: Final[str] = r"NORMAL_TEXTURE|NORMAL"
METALLIC_TEXTURE_LABEL_PATTERN: Final[str] = r"METALLIC_TEXTURE|METALLIC"
ROUGHNESS_TEXTURE_LABEL_PATTERN: Final[str] = r"ROUGHNESS_TEXTURE|ROUGHNESS"
ALPHA_TEXTURE_LABEL_PATTERN: Final[str] = r"ALPHA_TEXTURE|ALPHA"
AO_TEXTURE_LABEL_PATTERN: Final[str] = r"AO_TEXTURE|OCCLUSION|AO"
EMISSIVE_TEXTURE_LABEL_PATTERN: Final[str] = r"EMISSIVE_TEXTURE|EMISSIVE"
ALBEDO_TRIPLANAR_TEXTURE_LABEL_PATTERN: Final[str] = r"ALBEDO_TRIPLANAR_TEXTURE"
NORMAL_TRIPLANAR_TEXTURE_LABEL_PATTERN: Final[str] = r"NORMAL_TRIPLANAR_TEXTURE"
METALLIC_TRIPLANAR_TEXTURE_LABEL_PATTERN: Final[str] = r"METALLIC_TRIPLANAR_TEXTURE"
ROUGHNESS_TRIPLANAR_TEXTURE_LABEL_PATTERN: Final[str] = r"ROUGHNESS_TRIPLANAR_TEXTURE"
ALPHA_TRIPLANAR_TEXTURE_LABEL_PATTERN: Final[str] = r"ALPHA_TRIPLANAR_TEXTURE"
AO_TRIPLANAR_TEXTURE_LABEL_PATTERN: Final[str] = r"AO_TRIPLANAR_TEXTURE"
EMISSIVE_TRIPLANAR_TEXTURE_LABEL_PATTERN: Final[str] = r"EMISSIVE_TRIPLANAR_TEXTURE"

ALBEDO_TEXTURE_LABEL_REGEX: Final[re.Pattern[str]] = _compile_label_regex(ALBEDO_TEXTURE_LABEL_PATTERN)
NORMAL_TEXTURE_LABEL_REGEX: Final[re.Pattern[str]] = _compile_label_regex(NORMAL_TEXTURE_LABEL_PATTERN)
METALLIC_TEXTURE_LABEL_REGEX: Final[re.Pattern[str]] = _compile_label_regex(METALLIC_TEXTURE_LABEL_PATTERN)
ROUGHNESS_TEXTURE_LABEL_REGEX: Final[re.Pattern[str]] = _compile_label_regex(ROUGHNESS_TEXTURE_LABEL_PATTERN)
ALPHA_TEXTURE_LABEL_REGEX: Final[re.Pattern[str]] = _compile_label_regex(ALPHA_TEXTURE_LABEL_PATTERN)
AO_TEXTURE_LABEL_REGEX: Final[re.Pattern[str]] = _compile_label_regex(AO_TEXTURE_LABEL_PATTERN)
EMISSIVE_TEXTURE_LABEL_REGEX: Final[re.Pattern[str]] = _compile_label_regex(EMISSIVE_TEXTURE_LABEL_PATTERN)
ALBEDO_TRIPLANAR_TEXTURE_LABEL_REGEX: Final[re.Pattern[str]] = _compile_label_regex(ALBEDO_TRIPLANAR_TEXTURE_LABEL_PATTERN)
NORMAL_TRIPLANAR_TEXTURE_LABEL_REGEX: Final[re.Pattern[str]] = _compile_label_regex(NORMAL_TRIPLANAR_TEXTURE_LABEL_PATTERN)
METALLIC_TRIPLANAR_TEXTURE_LABEL_REGEX: Final[re.Pattern[str]] = _compile_label_regex(METALLIC_TRIPLANAR_TEXTURE_LABEL_PATTERN)
ROUGHNESS_TRIPLANAR_TEXTURE_LABEL_REGEX: Final[re.Pattern[str]] = _compile_label_regex(ROUGHNESS_TRIPLANAR_TEXTURE_LABEL_PATTERN)
ALPHA_TRIPLANAR_TEXTURE_LABEL_REGEX: Final[re.Pattern[str]] = _compile_label_regex(ALPHA_TRIPLANAR_TEXTURE_LABEL_PATTERN)
AO_TRIPLANAR_TEXTURE_LABEL_REGEX: Final[re.Pattern[str]] = _compile_label_regex(AO_TRIPLANAR_TEXTURE_LABEL_PATTERN)
EMISSIVE_TRIPLANAR_TEXTURE_LABEL_REGEX: Final[re.Pattern[str]] = _compile_label_regex(EMISSIVE_TRIPLANAR_TEXTURE_LABEL_PATTERN)
LIGHTMAP_PIXELS_PER_METER: Final[int] = 128
LIGHTMAP_MAX_RESOLUTION: Final[int] = 1024
BAKE_SAMPLES: Final[int] = 2560
BAKE_MARGIN: Final[int] = 4
EXCLUDED_COLLECTIONS: Final[set[str]] = {'COLLIDERS', 'COMMANDS'}
